### ISSUE TITLE
 Unnecessary world-writable permissions for Auto-Update

### ISSUE THREAD

**Issue by violentinternet** [mfonville/android-studio#1]
The whole software installed into /opt world-writeable in order the Auto-Updater to work. What is the point using Auto-Updater if you package a software by your self.

This not only contradicts FSH but is a security issue in general. Please remove the CHMODs in postinstall.

**Comment by mfonville** [comment]
@violentinternet unfortunately Android Studio is so badly programmed that it gives errors at startup if the directory is not writable. And I had investigated, but is not possible, to disable the auto-updater from outside the application. Only the user itself can manually disable it.

So even though the world write-able directory is not desirable, it is least the worst choice at the moment from the user friendliness perspective.

**Comment by violentinternet** [comment]
Maybe this was the case a long time ago. Meanwhile Android-Studio is packaged on many distros without world writeable files. Just looked at Arch package which I use myself and Gentoo builds. None of them does this.

I tried it on our machines it does not give anything into stdout/-err. Could you give me an error message if you can reproduce this? I would create a ticket at vendor's since this is clearly an unintended situation. This basically gives arbitrary code execution under different UserID in multi-user environments when somebody starts Android-Studio.

Thx in advance.

**Comment by mfonville** [comment]
@violentinternet it did so when I was making the initial version of the package, that is 2 months ago. If it doesn't happen anymore, we an of course remove the `chmod`. Could you verify that Arch and Gentoo don't apply any patches to suppress these errors or remove the updater?

As I currently lack the time to test & reproduce myself (really busy). If you are sure no errors to be expected, just give a PR and I will merge it in.

**Comment by violentinternet** [comment]
Done. The PR is inspired by AUR package: 
``chmod ugo+rX -R /opt/android-studio``
From manpage: 
`` execute/search only if the file is a directory or already has execute permission for some user (X)``
So an elegant way to ensure everything has the needed exec-permissions.

I gone through the ebuild and the AUR package. The don't do anything special, no patches or alike. I gone through different versions down to v1.5 oft the AUR packages(there's a git) and didn't find anything alike either.
