### ISSUE TITLE
Update PPA pre-built version to latest

### ISSUE THREAD

**Issue by jerome-benoit** [mfonville/android-studio#10]
The current version in PPA is rather outdated. 

Thanks.

**Comment by mfonville** [comment]
Yeah, Google's website had changed and the script had to be updated to accommodate, it should be ok now.

**Comment by jerome-benoit** [comment]
> Le 15 sept. 2019 à 21:06, Maarten Fonville <notifications@github.com> a écrit :
> 
> Yeah, Google's website had changed and the script had to be updated to accommodate, it should be ok now.
> 
Great ! Many thanks.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3
