### ISSUE TITLE
Official Repo From Google? 

### ISSUE THREAD

**Issue by RealCerealKiller** [mfonville/android-studio#6]
Hi @mfonville,
thank you so much for your awesome and extremely useful [PPA](https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio)! 👍
Do you know if @google has an own PPA for [Android Studio](https://developer.android.com/studio/index.html) or if it will become part of the official @ubuntu one? I do not want to say that I do not trust you, but something official would be sweet though... 🤔

**Comment by mfonville** [comment]
Google doesn't offer a PPA and I wouldn't expect it (as it is closed source) to become part of the Ubuntu repositories.

If you want to, you can use the scripts in this repository to spin your own builds / PPA-packages. Though the packages are mostly a wrapper anyhow
