### ISSUE TITLE
fails to install on default xenial without /opt

### ISSUE THREAD

**Issue by azrdev** [mfonville/android-studio#7]
Tried to install `android-studio` from your PPA on an ubuntu 16.04 xenial, which failed with error message `subprocess pre-installation script returned error exit status 1`

Turns out the script tries to download to `/opt` which [doesn't necessarily exist](https://askubuntu.com/a/604207). Maybe `/tmp` would be a better idea, maybe there's a packaging guideline for this?

**Comment by mfonville** [comment]
Thanks for your feedback, `/tmp` would indeed be better for the temporary download; I currently have no time at hand, but I would merge a PR that would change this
